trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'Deployment Variables'
  - name: NODE_VERSION
    value: '24.x'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Use Node.js'

- script: |
    npm install
    npm ci
    npm run build
    cp staticwebapp.config.json build/staticwebapp.config.json
  displayName: 'Build (Vite -> build/)'

- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment_token)
    app_location: 'build'     # <-- upload this folder
    output_location: ''       # <-- must be empty when skip_app_build=true
    api_location: ''
    skip_app_build: true
    skip_api_build: true
